const PROFILES = [
  {
    id: 1,
    name: 'Mara',
    emoji: '🧭',
    accent: '#2a9df4',
    status: 'First Mate',
    line: 'Knows every sketchy shortcut.',
    bio: 'Will say "trust me" and somehow be right. Smells faintly of salt and stolen lemons.',
    tags: ['shortcut gremlin', 'lemons', 'row faster'],
    isSiren: false,
  },
  {
    id: 2,
    name: 'Calypso',
    emoji: '🧜‍♀️',
    accent: '#ff637d',
    status: 'Siren',
    line: 'Smiles like a scam.',
    bio: 'Shows up in perfect lighting and says "u up?" with a wave behind it.',
    tags: ['bad idea', 'pretty fishy', 'absolutely not'],
    isSiren: true,
    sirenReveal: 'oh no. that was a siren. the app got you, the sea got louder, and your gold is doing laps now.',
  },
  {
    id: 3,
    name: 'Finn',
    emoji: '🦜',
    accent: '#53b36b',
    status: 'Parrot Dad',
    line: 'Parrot has better taste than him.',
    bio: 'Keeps snacks in every pocket and the bird is definitely the one making the decisions.',
    tags: ['bird approved', 'snacks', 'tiny chaos'],
    isSiren: false,
  },
  {
    id: 4,
    name: 'Rhea',
    emoji: '🌊',
    accent: '#4f8ef7',
    status: 'Wave Rider',
    line: 'Always wet. For context: the sea.',
    bio: 'Will absolutely make you follow the moonlight trail and then act like that was normal.',
    tags: ['moon trail', 'wet shoes', 'bad impulse'],
    isSiren: false,
  },
  {
    id: 5,
    name: 'Isadora',
    emoji: '🔱',
    accent: '#d961ff',
    status: 'Siren',
    line: 'Too polished. Suspicious.',
    bio: 'The profile pic looks edited by the ocean itself and that is honestly worse.',
    tags: ['glow up', 'water problem', 'do not'],
    isSiren: true,
    sirenReveal: 'yep. another siren. you tapped the shiny one and the ocean said lol.',
  },
  {
    id: 6,
    name: 'Drake',
    emoji: '⚔️',
    accent: '#f59f4c',
    status: 'Privateer',
    line: 'Has a face that starts trouble.',
    bio: 'Will fix your hull, your mood, and then somehow make the whole thing someone else’s fault.',
    tags: ['duels', 'bad influence', 'ship fix'],
    isSiren: false,
  },
  {
    id: 7,
    name: 'Bellamy',
    emoji: '🍲',
    accent: '#19b6a6',
    status: 'Cook',
    line: 'Will feed you then roast you.',
    bio: 'Makes soup that could end a mutiny and pies that raise a few questions.',
    tags: ['galley menace', 'good soup', 'questionable pie'],
    isSiren: false,
  },
  {
    id: 8,
    name: 'Nerys',
    emoji: '🐚',
    accent: '#7f8cff',
    status: 'Moonlit',
    line: 'Smells like the tide.',
    bio: 'Very calm. Way too calm. Keeps staring at the water like it owes her money.',
    tags: ['tide talk', 'moon problem', 'uh oh'],
    isSiren: true,
    sirenReveal: 'yeah that was a siren. you did the wrong swipe and now the sea is laughing at you.',
  },
];
